### ISSUE TITLE
Possible tmp bug

### ISSUE THREAD

**Issue by tabicat444** [gaborcsardi/lpSolve#8]
When saving an lp object, I noticed that under $tmp, there's a note saying "Nobody will ever look at this" (text color is my own). Well, I looked at it and figured I should let you know it's still there. Thanks for your work!
![image](https://user-images.githubusercontent.com/29055258/109562280-08b82880-7a93-11eb-8dab-778051dd24de.png)

**Comment by gaborcsardi** [comment]
I am the maintainer, not the author, but 😆
